### ISSUE TITLE
3D Sphere with Source

### ISSUE THREAD

**Issue by tomasjames** [tomasjames/SFProject#1]
The next major task is to build upon the 2D sphere and generate a 3D sphere with a number of complications. 

This 3D sphere must have both a density and a temperature profile (i.e. be non-uniform, unlike the examples thus far). The density profile should go as 1/r^2 and the temperature profile should go as e.g.  rT (i.e. increasing with radius).

Behind this sphere (acting as a synthetic molecular cloud) there should be a star, or some other source, that illuminates the cloud, thus acting as a source under which the radiative transfer of the cloud (using ray tracing) can be analysed.

Furthermore an opacity law should be present, such as (v/v0)^ß.

**Comment by tomasjames** [comment]
Problems still remain with 3D sphere. Rendering seems to still occur in 2D rather than 3D. Cornelius Dullemond has been emailed to check whether my code is incorrect, or whether the code itself is buggy in this respect.

**Comment by tomasjames** [comment]
Since the last update, several revisions and additions have been made, most notably the addition of a script to generate custom .inp files. Those files are:
- amr_grid.inp
- dust_density.inp
- dust_temperature.inp
- dustkappa_silicate.inp

These are all read into RADMC-3D, however some complications are still present. By running the standard example with dustkappa_silicate.inp, the new opacities are read and work. Likewise, the other files are read but RADMC-3D generates a `ValueError: zero-size array to reduction operation minimum which has no identity` error.

**Comment by tomasjames** [comment]
All issues regarding this have been fixed (with the exception of the plot still being in 2D, not 3D as needed). Closing this issue.

**Comment by paulcclark** [comment]
Just seen the plot! Looks good! :) Could you try without the star? That way we might see more of the cloud. Should also try to get RADMC to make images in lots of different wavelengths too, so we can start to explore faking the Herschel bands...

**Comment by tomasjames** [comment]
Thanks Paul :). Wilco - I’ll give it a shot!

**Comment by paulcclark** [comment]
This might help. You need the extended transmission curve for the SPIRE bands (PSW_ext, PMW_ext, PLW_ext... the S, M, L is short medium long, I think...)

http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse&gname=Herschel&gname2=SPIRE

**Comment by paulcclark** [comment]
Anyway, these should give you an idea of what wavelengths we need. I don't think we need too many points for each band pass though... maybe 60, or so?
